/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.kcr_picko;

import java.awt.Label;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;


/**
 *
 * @author yannick
 */
public class AddNewPizza extends javax.swing.JFrame {
    
    private double pizzaValue;
    private double dodatkiValue;
    private double sizeValue;
    
    private String pizzaName;
    private ArrayList<String> addons;
    private String pizzaSize;
    
    private static final DecimalFormat df = new DecimalFormat("0.00");


    /**
     * Creates new form AddNewPizza
     */
    public AddNewPizza() {
        initComponents();
        
        pizzaValue = 0.0;
        sizeValue = 0.0;
        dodatkiValue = 0.0;
        
        pizzaName = "";
        addons = new ArrayList<String>();
        pizzaSize = "Srednja";
        
        srednjaRadioButton.setSelected(true);
    }
    
    private boolean noPizzaSelected(){
        return !(margaritaRadioButton.isSelected() || klasicanRadioButton.isSelected()
                || kraskaRadioButton.isSelected() || hawaiiRadioButton.isSelected()
                || pekocaRadioButton.isSelected() || morskaRadioButton.isSelected());
    }
    
    private void uncheckAllAddons(){
        articokeCheckBox.setSelected(false);
        buckeCheckBox.setSelected(false);
        cebulaCheckBox.setSelected(false);
        jajceCheckBox.setSelected(false);
        koruzaCheckBox.setSelected(false);
        kislaSmetanaCheckBox.setSelected(false);
        paprikaCheckBox.setSelected(false);
        prsutCheckBox.setSelected(false);
            }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pizzeButtonGroup = new javax.swing.ButtonGroup();
        sizeButtonGroup = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        margaritaPrice = new javax.swing.JLabel();
        pekocaPrice = new javax.swing.JLabel();
        kraskaPrice = new javax.swing.JLabel();
        morskaPrice = new javax.swing.JLabel();
        klasicnaPrice = new javax.swing.JLabel();
        hawaiiPrice = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        koruzaCheckBox = new javax.swing.JCheckBox();
        kislaSmetanaCheckBox = new javax.swing.JCheckBox();
        jajceCheckBox = new javax.swing.JCheckBox();
        articokeCheckBox = new javax.swing.JCheckBox();
        buckeCheckBox = new javax.swing.JCheckBox();
        cebulaCheckBox = new javax.swing.JCheckBox();
        prsutCheckBox = new javax.swing.JCheckBox();
        paprikaCheckBox = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        margaritaRadioButton = new javax.swing.JRadioButton();
        kraskaRadioButton = new javax.swing.JRadioButton();
        klasicanRadioButton = new javax.swing.JRadioButton();
        pekocaRadioButton = new javax.swing.JRadioButton();
        hawaiiRadioButton = new javax.swing.JRadioButton();
        morskaRadioButton = new javax.swing.JRadioButton();
        malaRadioButton = new javax.swing.JRadioButton();
        srednjaRadioButton = new javax.swing.JRadioButton();
        velikaRadioButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dodajButton = new javax.swing.JButton();
        cenaValue = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dodajButton1 = new javax.swing.JButton();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Pice:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Dodatki:");

        margaritaPrice.setText("7.90  €");

        pekocaPrice.setText("9.30  €");

        kraskaPrice.setText("9.80  €");

        morskaPrice.setText("9.70  €");

        klasicnaPrice.setText("9.00  €");

        hawaiiPrice.setText("8.90  €");

        jLabel3.setText("+ 1.50 € Na vsak dodatek.");

        koruzaCheckBox.setForeground(new java.awt.Color(0, 153, 255));
        koruzaCheckBox.setText("Koruza");
        koruzaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                koruzaCheckBoxActionPerformed(evt);
            }
        });

        kislaSmetanaCheckBox.setForeground(new java.awt.Color(0, 153, 255));
        kislaSmetanaCheckBox.setText("Kisla Smetana");
        kislaSmetanaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kislaSmetanaCheckBoxActionPerformed(evt);
            }
        });

        jajceCheckBox.setForeground(new java.awt.Color(0, 153, 255));
        jajceCheckBox.setText("Jajce");
        jajceCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jajceCheckBoxActionPerformed(evt);
            }
        });

        articokeCheckBox.setForeground(new java.awt.Color(0, 153, 255));
        articokeCheckBox.setText("Artičoke");
        articokeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                articokeCheckBoxActionPerformed(evt);
            }
        });

        buckeCheckBox.setForeground(new java.awt.Color(0, 153, 255));
        buckeCheckBox.setText("Bučke");
        buckeCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buckeCheckBoxActionPerformed(evt);
            }
        });

        cebulaCheckBox.setForeground(new java.awt.Color(0, 153, 255));
        cebulaCheckBox.setText("Čebula");
        cebulaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cebulaCheckBoxActionPerformed(evt);
            }
        });

        prsutCheckBox.setForeground(new java.awt.Color(0, 153, 255));
        prsutCheckBox.setText("Pršut");
        prsutCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prsutCheckBoxActionPerformed(evt);
            }
        });

        paprikaCheckBox.setForeground(new java.awt.Color(0, 153, 255));
        paprikaCheckBox.setText("Paprika");
        paprikaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paprikaCheckBoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Velikost:");

        pizzeButtonGroup.add(margaritaRadioButton);
        margaritaRadioButton.setForeground(new java.awt.Color(0, 153, 255));
        margaritaRadioButton.setText("Margarita");
        margaritaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                margaritaRadioButtonActionPerformed(evt);
            }
        });

        pizzeButtonGroup.add(kraskaRadioButton);
        kraskaRadioButton.setForeground(new java.awt.Color(0, 153, 255));
        kraskaRadioButton.setText("Kraška");
        kraskaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kraskaRadioButtonActionPerformed(evt);
            }
        });

        pizzeButtonGroup.add(klasicanRadioButton);
        klasicanRadioButton.setForeground(new java.awt.Color(0, 153, 255));
        klasicanRadioButton.setText("Klasična");
        klasicanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                klasicanRadioButtonActionPerformed(evt);
            }
        });

        pizzeButtonGroup.add(pekocaRadioButton);
        pekocaRadioButton.setForeground(new java.awt.Color(0, 153, 255));
        pekocaRadioButton.setText("Pekoča");
        pekocaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pekocaRadioButtonActionPerformed(evt);
            }
        });

        pizzeButtonGroup.add(hawaiiRadioButton);
        hawaiiRadioButton.setForeground(new java.awt.Color(0, 153, 255));
        hawaiiRadioButton.setText("Hawaii");
        hawaiiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hawaiiRadioButtonActionPerformed(evt);
            }
        });

        pizzeButtonGroup.add(morskaRadioButton);
        morskaRadioButton.setForeground(new java.awt.Color(0, 153, 255));
        morskaRadioButton.setText("Morska");
        morskaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                morskaRadioButtonActionPerformed(evt);
            }
        });

        sizeButtonGroup.add(malaRadioButton);
        malaRadioButton.setForeground(new java.awt.Color(0, 153, 255));
        malaRadioButton.setText("Mala");
        malaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malaRadioButtonActionPerformed(evt);
            }
        });

        sizeButtonGroup.add(srednjaRadioButton);
        srednjaRadioButton.setForeground(new java.awt.Color(0, 153, 255));
        srednjaRadioButton.setText("Srednja");
        srednjaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srednjaRadioButtonActionPerformed(evt);
            }
        });

        sizeButtonGroup.add(velikaRadioButton);
        velikaRadioButton.setForeground(new java.awt.Color(0, 153, 255));
        velikaRadioButton.setText("Velika");
        velikaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velikaRadioButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("- 1.00 €");

        jLabel6.setText("+ 0.00 €");

        jLabel7.setText("+ 2.00 €");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Cena: ");

        dodajButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        dodajButton.setText("Dodaj");
        dodajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajButtonActionPerformed(evt);
            }
        });

        cenaValue.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cenaValue.setText("0.00");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText(" €");

        dodajButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        dodajButton1.setText("Prekliči");
        dodajButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(srednjaRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(velikaRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(dodajButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dodajButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cenaValue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(margaritaPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(margaritaRadioButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(kraskaRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(klasicanRadioButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(kraskaPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(klasicnaPrice)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(pekocaPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(pekocaRadioButton))
                                .addGap(0, 0, 0)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(hawaiiRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(morskaRadioButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(hawaiiPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(morskaPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(kislaSmetanaCheckBox)
                                            .addComponent(koruzaCheckBox))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jajceCheckBox)
                                            .addComponent(articokeCheckBox))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(buckeCheckBox)
                                            .addComponent(cebulaCheckBox))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(prsutCheckBox)
                                            .addComponent(paprikaCheckBox)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(malaRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)))
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(margaritaRadioButton)
                    .addComponent(kraskaRadioButton)
                    .addComponent(klasicanRadioButton)
                    .addComponent(pekocaRadioButton)
                    .addComponent(hawaiiRadioButton)
                    .addComponent(morskaRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(margaritaPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kraskaPrice)
                    .addComponent(klasicnaPrice)
                    .addComponent(morskaPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pekocaPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hawaiiPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(koruzaCheckBox)
                            .addComponent(jajceCheckBox)
                            .addComponent(buckeCheckBox)
                            .addComponent(prsutCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kislaSmetanaCheckBox)
                            .addComponent(articokeCheckBox)
                            .addComponent(cebulaCheckBox)
                            .addComponent(paprikaCheckBox)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(malaRadioButton)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srednjaRadioButton)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(cenaValue)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(velikaRadioButton)
                    .addComponent(jLabel7)
                    .addComponent(dodajButton)
                    .addComponent(dodajButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        margaritaPrice.getAccessibleContext().setAccessibleName("MargaritaPriceLabel");
        pekocaPrice.getAccessibleContext().setAccessibleName("HawaiiPriceLAbel");
        kraskaPrice.getAccessibleContext().setAccessibleName("KlasicnaPriceLabel");
        morskaPrice.getAccessibleContext().setAccessibleName("PekocaPriceLabel");
        morskaPrice.getAccessibleContext().setAccessibleDescription("");
        klasicnaPrice.getAccessibleContext().setAccessibleName("KraskaLabel");
        hawaiiPrice.getAccessibleContext().setAccessibleName("MorskaPriceLAbel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void koruzaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_koruzaCheckBoxActionPerformed
        if (koruzaCheckBox.isSelected()){
            dodatkiValue += 1.5;
            addons.add(evt.getActionCommand());
            cenaValue.setText(df.format(pizzaValue + dodatkiValue + sizeValue));
        }
        else{
            dodatkiValue -= 1.5;
            addons.remove(evt.getActionCommand());
            cenaValue.setText(df.format(pizzaValue + dodatkiValue + sizeValue));    
        }
    }//GEN-LAST:event_koruzaCheckBoxActionPerformed

    private void jajceCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jajceCheckBoxActionPerformed
          
        if (jajceCheckBox.isSelected()){
            dodatkiValue += 1.5;
            addons.add(evt.getActionCommand());
            cenaValue.setText(df.format(pizzaValue + dodatkiValue + sizeValue));
        }
        else{
            dodatkiValue -= 1.5;
            addons.remove(evt.getActionCommand());
            cenaValue.setText(df.format(pizzaValue + dodatkiValue + sizeValue));    
        }
    }//GEN-LAST:event_jajceCheckBoxActionPerformed

    private void margaritaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_margaritaRadioButtonActionPerformed
        double margaritaValue = Double.parseDouble(margaritaPrice.getText().split(" ")[0]);
                
        pizzaValue = margaritaValue;
        pizzaName = "Margarita";
        
        cenaValue.setText(df.format(pizzaValue + dodatkiValue + sizeValue));
    }//GEN-LAST:event_margaritaRadioButtonActionPerformed
    
    private void dodajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajButtonActionPerformed
        
        if (noPizzaSelected()) {
            JOptionPane.showMessageDialog(null, "Prosim izperite pico ali kliknite Prekliči.");
        }
        else {
            Pizza pizza = new Pizza(pizzaName, addons, pizzaSize, pizzaValue + dodatkiValue + sizeValue);
        
            String addonsStr = pizza.getAddon().toString();
        
            String pizzaItem = String.format("%s %s ... Dodtaki: %s ... %s EUR",
                    pizza.getSize(), pizza.getName(), addonsStr.substring(1, addonsStr.length() - 1), df.format(pizza.getCena()));
        
        
            MainMenu.model.addElement(pizzaItem);
            MainMenu.pizzaList.setModel(MainMenu.model);
            MainMenu.pizzaObjList.add(pizza);
        
            double trenutnaSkupnaCena = Double.parseDouble(MainMenu.skupnaCena.getText());
            MainMenu.skupnaCena.setText(df.format(trenutnaSkupnaCena + pizza.getCena()));
        
            this.dispose();   
        }
    }//GEN-LAST:event_dodajButtonActionPerformed

    private void kraskaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kraskaRadioButtonActionPerformed
        double kraskaValue = Double.parseDouble(kraskaPrice.getText().split(" ")[0]);
        
        pizzaValue = kraskaValue;
        pizzaName = "Kraška";
        
        cenaValue.setText(Double.toString(pizzaValue + dodatkiValue + sizeValue));
    }//GEN-LAST:event_kraskaRadioButtonActionPerformed

    private void klasicanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_klasicanRadioButtonActionPerformed
        double klasicnaValue = Double.parseDouble(klasicnaPrice.getText().split(" ")[0]);
        
        pizzaValue = klasicnaValue;
        pizzaName = "Klasična";
        
        cenaValue.setText(df.format(pizzaValue + dodatkiValue + sizeValue));
    }//GEN-LAST:event_klasicanRadioButtonActionPerformed

    private void pekocaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pekocaRadioButtonActionPerformed
        double pekocaValue = Double.parseDouble(pekocaPrice.getText().split(" ")[0]);
        
        pizzaValue = pekocaValue;
        pizzaName = "Pekoča";
        
        cenaValue.setText(df.format(pizzaValue + dodatkiValue + sizeValue));
    }//GEN-LAST:event_pekocaRadioButtonActionPerformed

    private void hawaiiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hawaiiRadioButtonActionPerformed
        double hawaiiValue = Double.parseDouble(hawaiiPrice.getText().split(" ")[0]);
        
        pizzaValue = hawaiiValue;
        pizzaName = "Hawaii";
        
        cenaValue.setText(df.format(pizzaValue + dodatkiValue + sizeValue));
    }//GEN-LAST:event_hawaiiRadioButtonActionPerformed

    private void morskaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_morskaRadioButtonActionPerformed
        double morskaValue = Double.parseDouble(morskaPrice.getText().split(" ")[0]);
        
        pizzaValue = morskaValue;
        pizzaName = "Morska";
        
        cenaValue.setText(df.format(pizzaValue + dodatkiValue + sizeValue));
    }//GEN-LAST:event_morskaRadioButtonActionPerformed

    private void malaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malaRadioButtonActionPerformed
        sizeValue = -1.0;
        pizzaSize = "Mala";
        cenaValue.setText(df.format(pizzaValue + dodatkiValue + sizeValue));
    }//GEN-LAST:event_malaRadioButtonActionPerformed

    private void srednjaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srednjaRadioButtonActionPerformed
        sizeValue = 0.0;
        pizzaSize = "Srednja";
        cenaValue.setText(df.format(pizzaValue + dodatkiValue + sizeValue));
    }//GEN-LAST:event_srednjaRadioButtonActionPerformed

    private void velikaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velikaRadioButtonActionPerformed
        sizeValue = 2.0;
        pizzaSize = "Velika";
        cenaValue.setText(df.format(pizzaValue + dodatkiValue + sizeValue));
    }//GEN-LAST:event_velikaRadioButtonActionPerformed

    private void buckeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buckeCheckBoxActionPerformed
        if (buckeCheckBox.isSelected()){
            dodatkiValue += 1.5;
            addons.add(evt.getActionCommand());
            cenaValue.setText(df.format(pizzaValue + dodatkiValue + sizeValue));
        }
        else{
            dodatkiValue -= 1.5;
            addons.remove(evt.getActionCommand());
            cenaValue.setText(df.format(pizzaValue + dodatkiValue + sizeValue));    
        }
    }//GEN-LAST:event_buckeCheckBoxActionPerformed

    private void prsutCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prsutCheckBoxActionPerformed
       
        System.out.println(addons.toString());
        
        if (prsutCheckBox.isSelected()){
            dodatkiValue += 1.5;
            addons.add(evt.getActionCommand());
            cenaValue.setText(df.format(pizzaValue + dodatkiValue + sizeValue));
        }
        else{
            dodatkiValue -= 1.5;
            addons.remove(evt.getActionCommand());
            cenaValue.setText(df.format(pizzaValue + dodatkiValue + sizeValue));    
        }
    }//GEN-LAST:event_prsutCheckBoxActionPerformed

    private void kislaSmetanaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kislaSmetanaCheckBoxActionPerformed
        if (kislaSmetanaCheckBox.isSelected()){
            dodatkiValue += 1.5;
            addons.add(evt.getActionCommand());
            cenaValue.setText(df.format(pizzaValue + dodatkiValue + sizeValue));
        }
        else{
            dodatkiValue -= 1.5;
            addons.remove(evt.getActionCommand());
            cenaValue.setText(df.format(pizzaValue + dodatkiValue + sizeValue));    
        }
    }//GEN-LAST:event_kislaSmetanaCheckBoxActionPerformed

    private void articokeCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_articokeCheckBoxActionPerformed
        if (articokeCheckBox.isSelected()){
            dodatkiValue += 1.5;
            addons.add(evt.getActionCommand());
            cenaValue.setText(df.format(pizzaValue + dodatkiValue + sizeValue));
        }
        else{
            dodatkiValue -= 1.5;
            addons.remove(evt.getActionCommand());
            cenaValue.setText(df.format(pizzaValue + dodatkiValue + sizeValue));    
        }
    }//GEN-LAST:event_articokeCheckBoxActionPerformed

    private void cebulaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cebulaCheckBoxActionPerformed
        if (cebulaCheckBox.isSelected()){
            dodatkiValue += 1.5;
            addons.add(evt.getActionCommand());
            cenaValue.setText(df.format(pizzaValue + dodatkiValue + sizeValue));
        }
        else{
            dodatkiValue -= 1.5;
            addons.remove(evt.getActionCommand());
            cenaValue.setText(df.format(pizzaValue + dodatkiValue + sizeValue));    
        }
    }//GEN-LAST:event_cebulaCheckBoxActionPerformed

    private void paprikaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paprikaCheckBoxActionPerformed
        if (paprikaCheckBox.isSelected()){
            dodatkiValue += 1.5;
            addons.add(evt.getActionCommand());
            cenaValue.setText(df.format(pizzaValue + dodatkiValue + sizeValue));
        }
        else{
            dodatkiValue -= 1.5;
            addons.remove(evt.getActionCommand());
            cenaValue.setText(df.format(pizzaValue + dodatkiValue + sizeValue));    
        }
    }//GEN-LAST:event_paprikaCheckBoxActionPerformed

    private void dodajButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_dodajButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewPizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox articokeCheckBox;
    private javax.swing.JCheckBox buckeCheckBox;
    private javax.swing.JCheckBox cebulaCheckBox;
    private javax.swing.JLabel cenaValue;
    private javax.swing.JButton dodajButton;
    private javax.swing.JButton dodajButton1;
    private javax.swing.JLabel hawaiiPrice;
    private javax.swing.JRadioButton hawaiiRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox jajceCheckBox;
    private javax.swing.JCheckBox kislaSmetanaCheckBox;
    private javax.swing.JRadioButton klasicanRadioButton;
    private javax.swing.JLabel klasicnaPrice;
    private javax.swing.JCheckBox koruzaCheckBox;
    private javax.swing.JLabel kraskaPrice;
    private javax.swing.JRadioButton kraskaRadioButton;
    private javax.swing.JRadioButton malaRadioButton;
    private javax.swing.JLabel margaritaPrice;
    private javax.swing.JRadioButton margaritaRadioButton;
    private javax.swing.JLabel morskaPrice;
    private javax.swing.JRadioButton morskaRadioButton;
    private javax.swing.JCheckBox paprikaCheckBox;
    private javax.swing.JLabel pekocaPrice;
    private javax.swing.JRadioButton pekocaRadioButton;
    private javax.swing.ButtonGroup pizzeButtonGroup;
    private javax.swing.JCheckBox prsutCheckBox;
    private javax.swing.ButtonGroup sizeButtonGroup;
    private javax.swing.JRadioButton srednjaRadioButton;
    private javax.swing.JRadioButton velikaRadioButton;
    // End of variables declaration//GEN-END:variables
}
